use strict;
use warnings;
use Time::Check;
use Test::More tests => 4;
#指定の時刻が正しく判定されるかテストします
can_ok('Time::Check', 'check');

subtest 'Starthour < Endhour' => sub {
    my $time = new Time::Check(0,12);
    plan tests => 24;
    is($time->check(0),1);
    is($time->check(1),1);
    is($time->check(2),1);
    is($time->check(3),1);
    is($time->check(4),1);
    is($time->check(5),1);
    is($time->check(6),1);
    is($time->check(7),1);
    is($time->check(8),1);
    is($time->check(9),1);
    is($time->check(10),1);
    is($time->check(11),1);
    is($time->check(12),0);
    is($time->check(13),0);
    is($time->check(14),0);
    is($time->check(15),0);
    is($time->check(16),0);
    is($time->check(17),0);
    is($time->check(18),0);
    is($time->check(19),0);
    is($time->check(20),0);
    is($time->check(21),0);
    is($time->check(22),0);
    is($time->check(23),0);
};

subtest 'Starthour > Endhour' => sub {
    my $time = new Time::Check(18,6);
    plan tests => 24;
    is($time->check(0),1);
    is($time->check(1),1);
    is($time->check(2),1);
    is($time->check(3),1);
    is($time->check(4),1);
    is($time->check(5),1);
    is($time->check(6),0);
    is($time->check(7),0);
    is($time->check(8),0);
    is($time->check(9),0);
    is($time->check(10),0);
    is($time->check(11),0);
    is($time->check(12),0);
    is($time->check(13),0);
    is($time->check(14),0);
    is($time->check(15),0);
    is($time->check(16),0);
    is($time->check(17),0);
    is($time->check(18),1);
    is($time->check(19),1);
    is($time->check(20),1);
    is($time->check(21),1);
    is($time->check(22),1);
    is($time->check(23),1);
};

subtest 'Starthour = endhour' => sub {
    my $time = new Time::Check(0,0);
    plan tests => 24;
    is($time->check(0),1);
    is($time->check(1),0);
    is($time->check(2),0);
    is($time->check(3),0);
    is($time->check(4),0);
    is($time->check(5),0);
    is($time->check(6),0);
    is($time->check(7),0);
    is($time->check(8),0);
    is($time->check(9),0);
    is($time->check(10),0);
    is($time->check(11),0);
    is($time->check(12),0);
    is($time->check(13),0);
    is($time->check(14),0);
    is($time->check(15),0);
    is($time->check(16),0);
    is($time->check(17),0);
    is($time->check(18),0);
    is($time->check(19),0);
    is($time->check(20),0);
    is($time->check(21),0);
    is($time->check(22),0);
    is($time->check(23),0);
};

